"""Stack copy logic for bootstrap (extracted from bootstrap_copy.py).

Each built-in stack lives in `<lib_dir>/stacks/<name>/{stack.json, guide.md}`.
Legacy fallback: `<lib_dir>/harness/stacks/<name>.md` for stacks that haven't
migrated yet — bootstrap stays compatible with partial-migration repos.
"""

from __future__ import annotations

import os
import shutil

# Each stack pulls its own decl/guide plus any base-stack guide.
# Used both for the new layout (dir copy) and the legacy flat fallback.
_STACK_DEPS: dict[str, list[str]] = {
    "python": ["python"],
    "fastapi": ["fastapi", "python"],
    "django": ["django", "python"],
    "flask": ["flask", "python"],
    "react": ["react"],
    "next": ["next", "react"],
    "vue": ["vue"],
    "nuxt": ["nuxt", "vue"],
    "svelte": ["svelte"],
    "typescript": ["typescript"],
    "javascript": ["javascript"],
    "go": ["go"],
    "rust": ["rust"],
    "java": ["java"],
    "kotlin": ["kotlin", "java"],
    "swift": ["swift"],
    "flutter": ["flutter"],
    "laravel": ["laravel", "php"],
    "php": ["php"],
    "blade": ["blade", "php"],
    "ansible": ["ansible"],
    "terraform": ["terraform"],
    "helm": ["helm"],
    "kubernetes": ["kubernetes"],
    "docker": ["docker"],
}


def _resolve_legacy_src(lib_dir: str, ide: str) -> str | None:
    for path in (
        os.path.join(lib_dir, "harness", "stacks"),
        os.path.join(lib_dir, "harness", ide, "stacks"),
        os.path.join(lib_dir, "harness", "claude", "stacks"),
    ):
        if os.path.isdir(path):
            return path
    return None


def copy_stacks(lib_dir: str, target_dir: str, ide: str, detected_stacks: list[str]) -> int:
    """Copy stack declarations + guides into `<target_dir>/stacks/<name>/`.

    Always copies `stacks/_schema.json` so registry validation works.
    Returns the number of stacks copied (counts each stack once whether
    via new layout or legacy fallback).
    """
    new_root = os.path.join(lib_dir, "stacks")
    legacy_src = _resolve_legacy_src(lib_dir, ide)

    if not os.path.isdir(new_root) and legacy_src is None:
        return 0

    stacks_dst = os.path.join(target_dir, "stacks")
    os.makedirs(stacks_dst, exist_ok=True)

    if detected_stacks:
        wanted: set[str] = set()
        for stack in detected_stacks:
            wanted.update(_STACK_DEPS.get(stack.lower(), [stack.lower()]))
        if any(s in detected_stacks for s in ("react", "next", "vue", "nuxt", "svelte")):
            wanted.add("typescript")
    else:
        wanted = _all_known_stacks(new_root, legacy_src)

    count = 0
    for stack_name in wanted:
        # Prefer new layout: stacks/<name>/ → .claude/stacks/<name>/
        new_dir = os.path.join(new_root, stack_name)
        if os.path.isdir(new_dir):
            dst_dir = os.path.join(stacks_dst, stack_name)
            os.makedirs(dst_dir, exist_ok=True)
            for fname in os.listdir(new_dir):
                src_f = os.path.join(new_dir, fname)
                if os.path.isfile(src_f):
                    shutil.copy2(src_f, os.path.join(dst_dir, fname))
            count += 1
            continue
        # Legacy fallback: harness/stacks/<name>.md → .claude/stacks/<name>.md
        if legacy_src is None:
            continue
        legacy_md = os.path.join(legacy_src, f"{stack_name}.md")
        if os.path.isfile(legacy_md):
            shutil.copy2(legacy_md, os.path.join(stacks_dst, f"{stack_name}.md"))
            count += 1

    # Ship the stack-decl JSON Schema so user override authors can validate.
    schema_src = os.path.join(new_root, "_schema.json")
    if os.path.isfile(schema_src):
        shutil.copy2(schema_src, os.path.join(stacks_dst, "_schema.json"))

    return count


# One canonical MCP source. `copy_mcp` falls back to harness/claude/mcp for every IDE
# that has no tree of its own, which is now all of them — so there is exactly one
# tools.py to regenerate, and no mirror that can drift out of sync with it.
_MCP_TOOLS_PATHS = ("harness/claude/mcp/project/tools.py",)
_STACKS_BEGIN = "# === BEGIN STACKS_ENUM (auto-generated by bootstrap from stack_registry) ==="
_STACKS_END = "# === END STACKS_ENUM ==="


def regenerate_mcp_stack_enums(lib_dir: str) -> int:
    """Rewrite the `_STACKS_ENUM` block in MCP tools.py files from the registry.

    Each tools.py contains a fenced block:
        # === BEGIN STACKS_ENUM ...
        _STACKS_ENUM = [...]
        # === END STACKS_ENUM ===
    We replace that block with a freshly-sorted list pulled from the
    plugin registry. Files without the markers are skipped (back-compat
    with older agent layouts). Returns the number of files updated.
    """
    import sys as _sys

    try:
        scripts_dir = os.path.join(lib_dir, "scripts")
        if scripts_dir not in _sys.path:
            _sys.path.insert(0, scripts_dir)
        from stack_registry import default_registry

        names = sorted(default_registry().all_stacks())
    except Exception:  # noqa: BLE001
        return 0
    if not names:
        return 0

    new_block = _STACKS_BEGIN + "\n"
    new_block += (
        "# Do not edit by hand — bootstrap rewrites this list from stacks/<name>/stack.json.\n"
    )
    new_block += "# Hand edits will be overwritten on the next `python bootstrap/bootstrap.py`.\n"
    new_block += "_STACKS_ENUM = [\n"
    for n in names:
        new_block += f'    "{n}",\n'
    new_block += "]\n"
    new_block += _STACKS_END

    updated = 0
    for rel in _MCP_TOOLS_PATHS:
        path = os.path.join(lib_dir, rel)
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        if _STACKS_BEGIN not in text or _STACKS_END not in text:
            continue
        before, _, rest = text.partition(_STACKS_BEGIN)
        _, _, after = rest.partition(_STACKS_END)
        new_text = before + new_block + after
        if new_text != text:
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_text)
            updated += 1
    return updated


def _all_known_stacks(new_root: str, legacy_src: str | None) -> set[str]:
    """Union of stack names visible across both layouts (skip hidden/_internal)."""
    out: set[str] = set()
    if os.path.isdir(new_root):
        out.update(
            d
            for d in os.listdir(new_root)
            if os.path.isdir(os.path.join(new_root, d)) and not d.startswith((".", "_"))
        )
    if legacy_src is not None and os.path.isdir(legacy_src):
        out.update(f[:-3] for f in os.listdir(legacy_src) if f.endswith(".md"))
    return out
