@echo off
REM TAUSIK CLI wrapper — always uses .tausik/venv Python
REM Generated by bootstrap. Do not edit manually.

setlocal
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."

REM Force UTF-8 stdio so Unicode output (Cyrillic, checkmarks) never hits a
REM cp1251/cp1252 console encoder and raises UnicodeEncodeError on Windows.
set "PYTHONUTF8=1"

REM Find scripts dir. IDE list injected from bootstrap_config.IDE_DIRS
REM (single source of truth) by install_cli_wrapper.
set "IDE_LIST=__IDE_LIST__"
set "SCRIPTS="
for %%I in (%IDE_LIST%) do (
    if not defined SCRIPTS if exist "%PROJECT_DIR%\.%%I\scripts" set "SCRIPTS=%PROJECT_DIR%\.%%I\scripts"
)
REM goto (not an inline block) so literal parens in the error text can't
REM prematurely close the if-block and make exit unconditional. (v153 Windows fix)
if not defined SCRIPTS goto :noscripts

REM Find Python: prefer .tausik/venv
if exist "%SCRIPT_DIR%venv\Scripts\python.exe" (
    set "PYTHON=%SCRIPT_DIR%venv\Scripts\python.exe"
) else (
    set "PYTHON=python"
)

"%PYTHON%" "%SCRIPTS%\project.py" %*
exit /b %ERRORLEVEL%

:noscripts
echo Error: no scripts dir found ^(none of: %IDE_LIST% under .^<ide^>\scripts^) 1>&2
exit /b 1
